version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --kms-key-id arn:aws:kms:us-east-1:575761299872:key/1973d5ec-7abc-472a-9368-2b50f3a45aef --s3-bucket pdomala-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
